name: CI/CD Backend - Test, Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: angeel22m/clinica-backend
  PORT: 3000

jobs:
  # ----------------------------------
  # Tests Unitarios
  # ----------------------------------
  test:
    name: Ejecutar Tests Unitarios
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Instalar dependencias
        run: npm install

      - name: Correr Tests Unitarios
        run: npm run test

  # ----------------------------------
  # Build y Push de Docker (depende de tests)
  # ----------------------------------
  build_and_push:
    name: Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  # ----------------------------------
  # Despliegue Docker (depende del build)
  # ----------------------------------
  deploy:
    name: Deploy Docker Container
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Container
        run: |
          echo "Deteniendo contenedor anterior si existe..."
          docker stop clinica-backend-app || true
          docker rm clinica-backend-app || true

          echo "Iniciando contenedor con variables de entorno..."
          docker run -d --name clinica-backend-app \
            -p ${{ env.PORT }}:${{ env.PORT }} \
            -e NODE_ENV=production \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e FIREBASE_SERVICE_ACCOUNT_KEY="${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" \
            -e FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}" \
            ${{ env.IMAGE_NAME }}:latest
